CREATE TABLE SOLICITUD(
  ID_SOLICITUD INT(11) PRIMARY KEY ,
  CORREO VARCHAR(250),
  INGRESO DECIMAL(9,2),
  CANTIDAD DECIMAL(9,2),
  PLAZO INT(11),
  CANTIDAD_POSIBLE DECIMAL(9,2),
  PUNTOSBURO INT(11),
  CBURO CHAR(1),
  PUNTOSSAT INT(11),
  CSAT CHAR(1),
  CINGRESO CHAR(1),
  CALIFICACION CHAR(1),
  FECHA_SOLICITUD DATE,
  CONSTRAINT FK_SOLICITUD FOREIGN KEY (CORREO)
  REFERENCES CLIENTE(CORREO)
);
CREATE TABLE CLIENTE(
  NOMBRE VARCHAR(250),
  CORREO VARCHAR(250) PRIMARY KEY,
  TELEFONO  VARCHAR(250),
  FECHA_NACIMIENTO DATE
);
CREATE TABLE PRESTAMOS(
  ID_PRESTAMOS INT(11) PRIMARY KEY,
  ID_SOLICITUD INT(11),
  CANTIDAD DECIMAL(9,2),
  TOTAL DECIMAL(9,2),
  PLAZO INT(11),
  FECHA_PRESTAMO DATE,
  CONSTRAINT FK_PRESTAMO FOREIGN KEY (ID_SOLICITUD)
  REFERENCES SOLICITUD(ID_SOLICITUD)
);
CREATE TABLE PAGOS(
  ID_PRESTAMOS INT(11),
  FECHA DATE,
  CANTIDAD DECIMAL(9,2),
  CONSTRAINT PK_PAGOS PRIMARY KEY (ID_PRESTAMOS,FECHA),
  CONSTRAINT FK_PAGOS FOREIGN KEY (ID_PRESTAMOS)
  REFERENCES PRESTAMOS(ID_PRESTAMOS)
);
CREATE TABLE BLACKLIST(
  NOMBRE VARCHAR(250)
);
